twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/fab-admin': Fab-admin
        '%kernel.project_dir%/templates/fab-admin/componenti': Componenti
        '%kernel.project_dir%/templates/fab-admin/main/pages': Pagine

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
